services:
  # A Docker web service
  - type: web
    name: Test
    env: python
    startCommand: python3 bot.py
    buildCommand: pip3 install -U -r requirements.txt
    repo: https://github.com/skalight/Test.git 
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: rolex # optional (defaults to master)
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /
    envVars:
      - key: DATABASE_URI
        value: mongodb+srv://think:think@cluster015.9oqeden.mongodb.net/?retryWrites=true&w=majority
      - key: BOT_TOKEN
        value: 5452246619:AAFNDeo7112BsPm9600Z1NI57RCh-PYvltI
      - key: DATABASE_NAME
        value: test
#End of yaml
