services:
 - type: web
    name: rolex
    env: Python 3
    repo: https://github.com/skalight/Test
    plan: free
    region: oregon # optional (defaults to oregon)
    branch: rolex # optional (defaults to master)
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3bot.py"
    envVars:
      - key: DATABASE_URI
        fromDatabase:
          name: rolex
          property: connectionString
      - key: BOT_TOKEN
        generateValue: true
      - key: ADMIN_EMAIL
        value: 'spree@example.com'
