services:
  # A Docker web service
  - type: web
    name: Test
    env: python
    startCommand: python3 bot.py
    buildCommand: pip3 install -U -r requirements.txt
    repo: https://github.com/skalight/Test.git 
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: rolex # optional (defaults to master)
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spree
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: spree_redis
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: ADMIN_EMAIL
        value: 'spree@example.com'
      - key: ADMIN_PASSWORD
        value: 'spree123'
#End of yaml
